name: Increment Project Version
description: Increments a Project's semantic version to the next version at Pull Request time
branding:
  icon: chevrons-up
  color: blue
inputs:
  token:
    description: Personal access token for the GitHub account that will be used to make the API calls.
    required: true
  files:
    description: The files that contain the version number to increment.
    required: true
runs:
  using: node16
  main: dist/index.js
